[package]
name = "toxoid_cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "toxoid"  # This is the final CLI binary name
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
clap_derive = "4.5.18"
notify = "6.1.1"