[package]
name = "snake_runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maud = "0.25.0"
tiny_file_server = "0.1.5"
notify = "6.0.1"