[package]
name = "toxoid_sokol"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
image = "0.24.7"
sokol = { version="*", git="https://github.com/floooh/sokol-rust.git" }
toxoid_render = { version="*", path="../toxoid_render" }

[build-dependencies]
bindgen = "0.69.1"
cc = "1.0.83"
