[package]
name = "toxoid_wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmi = "0.32.0"
wat = "1.209.1"
toxoid_api = { path="../toxoid_api" }