[package]
name = "toxoid_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toxoid_api_macro = { path = "../toxoid_api_macro" }
