[package]
name = "snake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "snake"
crate-type = ["cdylib"]

[dependencies]
toxoid_ffi_macro = { path="../../../crates/toxoid_ffi_macro" }